AllCops:
  RubyInterpreters:
    - ruby
  Exclude:
    - '.config/**/*'
    - '.git/**/*'
    - '.idea/**/*'
    - 'attributes/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - '*.gitignore'
    - '*.md'
    - '*.yml'
    - 'Rakefile'
    -  '.travis.yml'
  DefaultFormatter: progress
  DisplayCopNames: true
  StyleGuideBaseURL: https://github.com/rubocop-hq/ruby-style-guide
  ExtraDetails: true
  StyleGuideCopsOnly: false
  EnabledByDefault: false
  DisabledByDefault: false
  UseCache: false
  TargetRubyVersion: 2.7

#################### Metrics ###############################
Metrics/LineLength:
  Enabled: false

#################### Style ###############################
Style/FrozenStringLiteralComment:
  Enabled: false